version: "3"
services:
    backend:
        build: backendFiles/.
        ports:
        - "8080:80"
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: data 
        volumes: 
            - ./dbdata2:/var/lib/mysql
            - ./dbInit:/docker-entrypoint-initdb.d/:ro
